# DS 3000/CS 3200 Lab 1

Due: Tuesday May 12 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub as per the instructions in Part 4, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

#### Note:
Future Labs/Homeworks do not need to be submitted via GitHub; I'm only asking you to do it on this Lab to practice with using GitHub (as it will be important to be familiar with its usage for the project). For some of you this is likely already second nature.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

You will use the markdown language in formatting parts of your project. Use it below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a working hyperlink to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.

# The Council of Europe
## Protecting Human Rights and the Rule of Law
### The European Court of Human Rights

![Palace of Europe](https://www.fiacat.org/images/categories/conseil-de-l-Europe-logo.jpg)

[Council of Europe](https://www.coe.int/en/web/portal) is an international organization founded in 1949, dedicated to upholding human rights, democracy, and the rule of law across its 46 member states.

## Key Facts

| Feature | Detail | Since |
|---|---|---|
| Founded | Treaty of London | 1949 |
| Headquarters | Strasbourg, France | 1949 |
| Member States | 46 countries | 2022 |
| Key Treaty | European Convention on Human Rights | 1953 |

## Core Pillars

- Human rights protection via the European Court of Human Rights
- Democratic governance and free elections
- Rule of law and judicial independence
- Cultural cooperation among member states


## Grade Calculation

$$grade = 0.40 \cdot \text{in-class activities} + 0.60 \cdot \text{homeworks and labs}

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [1]:
# make sure to import numpy library
import numpy as np



In [2]:
import numpy as np

array_a = np.array([
    [3,    8,  -2,  3],
    [0.5, -1,   6,  4],
    [-5,   7, -42,  2]
])

array_b = np.array([
    [ 42,  38,  34],
    [ 30,  26,  22],
    [ 18,  14,  10],
    [  6,   2,  -2],
    [ -6, -10, -14]
])


In [3]:
# uncomment below to print array_a
array_a


array([[  3. ,   8. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [4]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [5]:
for name, arr in [("array_a", array_a), ("array_b", array_b)]:
    print(f"{name}:")
    print(f"  shape:  {arr.shape}")
    print(f"  size:   {arr.size}")
    print(f"  ndim:   {arr.ndim}")
    print(f"  nbytes: {arr.nbytes}")
    print()

t_array_a = array_a.T
t_array_b = array_b.T

print(t_array_a)
print(t_array_b)

# Attempting to add array_a and t_array_b — this will FAIL
# array_a is (3,4) and t_array_b is (3,5) — shapes don't match
# array_a + t_array_b  # <-- uncomment to see the ValueError

# Remove the last column of t_array_b to make it (3,4)
t_array_b_trimmed = t_array_b[:, :-1]

# Now both are (3,4) — this works!
result = array_a + t_array_b_trimmed
print(result)

#The first addition failed with a `ValueError` because `array_a` has shape **(3, 4)** and `t_array_b` has shape **(3, 5)** — NumPy requires arrays to have matching shapes  (or compatible shapes for broadcasting) to perform element-wise addition.

# By removing the last column of `t_array_b` with `[:, :-1]`, we reduced it to shape **(3, 4)**, matching `array_a`, so the addition succeeded.

array_a:
  shape:  (3, 4)
  size:   12
  ndim:   2
  nbytes: 96

array_b:
  shape:  (5, 3)
  size:   15
  ndim:   2
  nbytes: 120

[[  3.    0.5  -5. ]
 [  8.   -1.    7. ]
 [ -2.    6.  -42. ]
 [  3.    4.    2. ]]
[[ 42  30  18   6  -6]
 [ 38  26  14   2 -10]
 [ 34  22  10  -2 -14]]
[[ 45.   38.   16.    9. ]
 [ 38.5  25.   20.    6. ]
 [ 29.   29.  -32.    0. ]]


# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [6]:
# make sure to import pandas library
import pandas as pd

In [7]:
import pandas as pd
df = pd.read_csv('train_stations_europe.csv', index_col='id')

print(df.head())

                       name   latitude  longitude  parent_station_id country  \
id                                                                             
1   Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN      FR   
2   Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0      FR   
3     Chateau-Arnoux Mairie  44.063863   6.011248                1.0      FR   
4           Digne-les-Bains  44.350000   6.350000                NaN      FR   
6           Digne-les-Bains  44.088710   6.222982                4.0      FR   

       time_zone  is_city  is_main_station  is_airport  
id                                                      
1   Europe/Paris     True            False       False  
2   Europe/Paris    False             True       False  
3   Europe/Paris    False            False       False  
4   Europe/Paris     True            False       False  
6   Europe/Paris    False             True       False  


## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [8]:
# (a) only Belgium, (b) exclude stations not in a city (drop rows where city is NaN)

import pandas as pd

df = pd.read_csv('train_stations_europe.csv', index_col='id')

# Part 3.1 - print first few rows
print(df.head())

# Part 3.2

# (a) only Belgium, (b) exclude stations not in a city (is_city == 1 means it is in a city)
belgium_df = df[(df['country'] == 'BE') & (df['is_city'] == 1)]

print(belgium_df.head())

# Summary statistics for belgium_df
print(belgium_df.describe())

#The `.describe()` function ran on the **numeric** columns only: `latitude`, `longitude`, `is_city`, `is_main_station`, and `is_airport`.

#It did **not** run on **string/object** columns like `name`, `country`, and `time_zone`, because operations like mean, std, and min/max are meaningless for text data.

#This means `.describe()` is used for **quickly summarizing the distribution of numerical data** — helpful for spotting outliers, checking value ranges, and understanding the overall shape of your numeric variables.

                       name   latitude  longitude  parent_station_id country  \
id                                                                             
1   Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN      FR   
2   Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0      FR   
3     Chateau-Arnoux Mairie  44.063863   6.011248                1.0      FR   
4           Digne-les-Bains  44.350000   6.350000                NaN      FR   
6           Digne-les-Bains  44.088710   6.222982                4.0      FR   

       time_zone  is_city  is_main_station  is_airport  
id                                                      
1   Europe/Paris     True            False       False  
2   Europe/Paris    False             True       False  
3   Europe/Paris    False            False       False  
4   Europe/Paris     True            False       False  
6   Europe/Paris    False             True       False  
                  name   latitude  longi

# Part 4: GitHub (10 points)

The below process is obviously not necessary, but designed to give students with minimal Git experience some practice using Git in the command line. When you finish the first three parts of this lab, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer26), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer26 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.
  - **Note**: you only have to do this for this assignment; future assignments can be uploaded directly to Gradescope